plone:
  image: eeacms/plone
  ports:
  - "80:80"
  links:
  - postgres
  environment:
  - BUILDOUT_EGGS=RelStorage psycopg2
  - BUILDOUT_REL_STORAGE=type postgresql \n host postgres \n dbname datafs \n user zope \n password zope

postgres:
  image: eeacms/postgres
  environment:
  - POSTGRES_DBNAME=datafs
  - POSTGRES_DBUSER=zope
  - POSTGRES_DBPASS=zope
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=secret
